update

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -44,4 +44,10 @@ jobs:
 
     - name: Test Hello World
       run: |
-        curl -f http://127.0.0.1:3000/ | grep 'Hello World'
+        OUTPUT=$(curl -f http://127.0.0.1:3000/)
+        if [[ "$OUTPUT" != "Hello World" ]]; then
+          echo "Test failed: Expected 'Hello World' but got '$OUTPUT'"
+          exit 1
+        else
+          echo "Test passed: Received 'Hello World'"
+        fi
